charset/charset.go
mysql/charset.go
parser.go
parser.y
types/field_type.go

Required for https://github.com/pingcap/tidb/pull/7965/

*: change default charset from utf8 to utf8mb4

---

mysql/const.go

Required for https://github.com/pingcap/tidb/issues/8128

mysql: NO_AUTO_CREATE_USER detect helper function

---

ast/expressions.go
parser.go
parser.y

This reverts commit 80638229692790da5b0152eb4d446738611f6efd.

Revert "parser,ast: fix the TiDB issue #8153 (#20)"

---

README.md

README: fix the format

---

README.md

Just like that
[![Go Report Card](https://goreportcard.com/badge/github.com/pingcap/parser)](https://goreportcard.com/report/github.com/pingcap/parser) [![CircleCI Status](https://circleci.com/gh/pingcap/parser.svg?style=shield)](https://circleci.com/gh/pingcap/parser) [![GoDoc](https://godoc.org/github.com/pingcap/parser?status.svg)](https://godoc.org/github.com/pingcap/parser)
@lysu

README: add `Go Report Card` and `CircleCI Status` badge

---

model/model.go

Refer: https://github.com/pingcap/tidb/pull/8181

model: add GetAutoIncrementColInfo for TableInfo

---

circle.yml

circle.yml: added a step to verify parser.go is up-to-date

---

charset/charset.go
charset/charset_test.go

cherry-pick from #66 
Required for https://github.com/pingcap/tidb/pull/8611

charset: make collation case insensitive (#66)

---

ast/expressions_test.go
ast/util_test.go

optimize restore unit test, add generic restore test logic

parser: optimize restore unit test

---

ast/expressions.go
ast/expressions_test.go

- implement Restore for PatternLikeExpr
Issue: [pingcap/tidb#8532](https://github.com/pingcap/tidb/issues/8532)

parser: implement Restore for PatternLikeExpr

---

ast/expressions.go
ast/expressions_test.go

Implement IsTruthExpr Restore
pingcap/tidb#8532

parser: Implement Restore for IsTruthExpr

---

ast/stats.go
parser_test.go

implement DropStatsStmt#Restore
pingcap/tidb#8532

parser: implement Restore for DropStatsStmt

---

ast/expressions.go
ast/expressions_test.go

implement Restore for PatternRegexpExpr
Issue: [pingcap/tidb#8532](https://github.com/pingcap/tidb/issues/8532)

parser: implement Restore for PatternRegexpExpr

---

parser.go
parser.y

Delete the outdate comment in #88 L2941

comment: remove the outdate comment

---

ast/ddl.go
ast/ddl_test.go

parser: implement Restore for TruncateTableStmt

---

ast/dml.go
ast/dml_test.go

Implement Restore and unit tests for HavingClause

parser: implement Restore for HavingClause

---

ast/misc.go
ast/stats.go
parser_test.go

* implement BeginStmt#Restore
* implement CommitStmt#Restore
* implement RollbackStmt#Restore
* implement AnalyzeTableStmt#Restore
* implement LoadStatsStmt#Restore
[pingcap/tidb#8532](https://github.com/pingcap/tidb/issues/8532)

parser: implement Restore for BeginStmt,CommitStmt,RollbackStmt, AnalyzeTableStmt and LoadStatsStmt

---

model/ddl.go

Cherry-pick #14 
for tidb https://github.com/pingcap/tidb/pull/8951

*: add ActionModifyTableCharsetAndCollate to support alter table charset and collate (#14)

---

circle.yml

download parser by commit hash in integration test.

ci: fix integration test of ci

---

ast/expressions.go
ast/expressions_test.go

Implement Restore and unit tests for ExistsSubqueryExpr

parser: implement Restore for ExistsSubqueryExpr

---

mysql/const.go

Cherry pick #171 to release 2.1

mysql: add sql mode ALLOW_INVALID_DATES (#171)

---

ast/dml.go
parser_test.go

parser: implement restore for UpdateStmt
pingcap/tidb#8532

parser: implement restore for UpdateStmt

---

ast/misc.go
parser_test.go

- implement Restore for `TraceStmt`
pingcap/tidb#8532

parser: implement Restore for TraceStmt

---

model/model.go

model: add IsAutoIncColUnsigned for TableInfo (#79)

---

model/model.go

cherry-pick https://github.com/pingcap/parser/pull/183
Tests

model: add version number to Column (#183)

---

model/model.go

Add version field to `tableInfo`.
Related tidb PR: pingcap/tidb#9480

model: add version field to tableInfo.

---

model/model.go

model: add version field to tableInfo. (#223)

---

auth/auth.go

Cherry-pick #227 to release 2.1 for uniform log format.

auth: use safe String() for UserIdentity (#227)

---

mysql/const.go

mysql: change MySQL version from 5.7.10 to 5.7.25

---

ast/dml.go
ast/dml_test.go
ast/functions_test.go
parser.go
parser.y
parser_test.go

Fix https://github.com/pingcap/tidb/pull/9567
Let parser can identify `over w` and `over (w)`.
Tests 
- Integration test with tidb.

ast: fix the behavior of window function

---

mysql/errcode.go
mysql/errname.go
terror/terror.go

cherry-pick #173 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/257)

mysql,terror: add plugin error msg (#173)

---

mysql/errcode.go
mysql/errname.go

Add an error type for write conflict.
Tests 
- Unit test
Code changes

mysql: add write conflict error

---

digester.go
digester_test.go
lexer.go

cherry-pick #215 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/279)

normalize and generate digest at same time (#215)

---

types/field_type.go
types/field_type_test.go

Cherry-pick https://github.com/pingcap/parser/pull/270

types: port 'HasCharset' function from MySQL (#270)

---

charset/charset.go

cherry-pick #294 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/296)

suspend unknown collation id 255 error (#294)

---

ast/functions_test.go
parser.go
parser.y

Cherry-pick https://github.com/pingcap/parser/pull/235 to convert charset name to lower-case.

type/compatibility: fix show create table output of generated column

---

mysql/errname.go

The message for ErrWriteConflict is outdated.
Add `writeConflictCommitTS` to the message.
Tests 
- No code

update error message of ErrWriteConflict

---

mysql/errcode.go
mysql/errname.go

This is part of [issue 7008](https://github.com/pingcap/tidb/issues/7008).
Add mysql standard error code 1907
Tests 
- No code
Code changes
Side effects

Add mysql standard error code 1907

---

model/flags.go

Signed-off-by: Lonng <heng@lonng.org>
Add a flag `FlagInUnionStmt` which is useful to cover some corner case in `CAST` functions implementation in the coprocessor.

model: add in union flag

---

opcode/opcode.go

opcode: fix literal string of operator `EQ` (#106)

---

ast/expressions.go
ast/format_test.go
opcode/opcode.go

cherry-pick #338.
merge https://github.com/pingcap/parser/pull/353 first.

 ast: fix case expression format bug (#338)

---

circle.yml

checkout to tidb release-3.0 branch when running integration test

checkout to tidb release-3.0 branch when running integration test

---

parser.go
parser.y
parser_test.go

Cherry-pick https://github.com/pingcap/parser/pull/366

parser: fix hint parsing in `select /*+ max_execution_time */ 1` (#366)

---

model/flags.go

add LoadData statement flag in model
add `FlagInLoadDataStmt` field in `model/flags.go`
Tests 
- None
Code changes
Side effects
- None
- https://github.com/pingcap/tidb/pull/11067

model: add LoadData statement flag

---

ast/misc.go

cherry-pick #487 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/511)

ast: add stmtType to ast.Prepared to record metric (#487)

---

mysql/const.go
parser.go
parser.y

Improve code readability.
Replace magic numbers in parser.y.
Tests 
- Unit test
Code changes

parser: replace magic numbers with meaningful names

---

ast/misc.go

add field for prepared statement to cache point get plan despite the prepared plan cache switch
the related tidb pull request [https://github.com/pingcap/tidb/pull/11970](link)
Tests 
- Unit test
Code changes
Side effects

executor: cache point get plan for prepared point 

---

parser.go
parser.y

parser: parse the fraction of CURRENT_TIMESTAMP default value (#211)

---

ast/functions.go
parser_test.go

cherry-pick https://github.com/pingcap/parser/pull/557
Tests 
- Unit test

ast/functions: add tidb_decode_plan() function (#557)

---

mysql/errcode.go
mysql/errname.go

add store limit error and name for PR [#12779](https://github.com/pingcap/tidb/pull/12779)
add error code and error name in mysql package
Tests 

parser: add error number for store limit error

---

mysql/errcode.go
mysql/errname.go

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
Add error code for types.

mysql: add error code for types

---

mysql/errcode.go
mysql/errname.go

parser: add a mysql error message (#534)

---

mysql/const.go
parser.go
parser.y

parser: replace magic numbers with meaningful names (#531)

---

mysql/errcode.go
mysql/errname.go

cherry-pick #612 to release-3.1
add error number for store limit error in mysql package
Tests 
Release note
- add error number for store limit error (#612)

parser : add error number for store limit error (#612)

---

mysql/errcode.go
mysql/errname.go

used by PR [ #12046](https://github.com/pingcap/tidb/pull/12046).
add mysql errorCode and errorName `ErrRepairTable`.
Tests 
- No code
Code changes
Side effects
- None
- None

parser : add errcode and errname for admin repair table.

---

model/ddl.go
parser.go
parser.y
parser_test.go

*: support primary key (#617)

---

parser.go
parser.y

parser: fix obscure error message in `bit(65)` column type (#530)

---

misc.go

Close #653.
Remove an unnecessary variable.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
N/A

remove an unnecessary variable

---

model/model.go

1. add a function GetTypeDesc for ColumnInfo
2. remove the function for Column https://github.com/pingcap/tidb/pull/13907/files#diff-1277eab0474a970f37a4ef86f3a339a4L236-L245
N/A
Tests 
- No code
Code changes
Side effects
N/A
N/A

model: add a function GetTypeDesc for ColumnInfo

---

model/model.go

cherry-pick #659 
1. add a function GetTypeDesc for ColumnInfo
2. remove the function for Column https://github.com/pingcap/tidb/pull/13907/files#diff-1277eab0474a970f37a4ef86f3a339a4L236-L245
N/A
Tests 
- No code
Code changes
Side effects
N/A
N/A

model: add a function GetTypeDesc for ColumnInfo (#659)

---

auth/auth_test.go
charset/charset_test.go
format/format_test.go
terror/terror_test.go
types/field_type_test.go

This is the first step to remove the dependency on TiDB. #677 
- remove testleak
Tests 
- Unit test
Code changes
N/A
Side effects
N/A

remove testleak

---

mysql/errcode.go
mysql/errname.go

mysql: add foreign key error (#675)

---

mysql/errcode.go
mysql/errname.go

Add auto_random error definitions for pingcap/tidb#13127.
Tests 
- Unit test
Code changes
Side effects

add auto_random error definitions

---

mysql/errcode.go
mysql/errname.go

mysql: add 2 infoschema related errors for TiDB (#595)

---

mysql/errcode.go
mysql/errname.go

cherry-pick #707
Tests 
- Unit test

parser : add invalid auto increment and offset error (#707)

---

model/model.go

fix json field name in #571 (#702)

---

mysql/errcode.go
mysql/errname.go
mysql/state.go

MySQL document: https://dev.mysql.com/doc/refman/8.0/en/server-error-reference.html#error_er_json_document_null_key

add json_objectagg's null key errcode

---

mysql/errname.go

Update the error message of `ErrCantGetValidID` for pingcap/tidb#14711.
Tests 
- Unit test
Code changes
Side effects

mysql/errname.go: update error message of ErrCantGetValidID

---

model/model.go

Signed-off-by: crazycs <crazycs520@gmail.com>
related TiDB PR: https://github.com/pingcap/tidb/pull/14735
Tests 
- No code

model: add partition replica available info to support partition table in tiflash.

---

model/model.go

Signed-off-by: crazycs <crazycs520@gmail.com>
cherry-pick https://github.com/pingcap/parser/pull/742

model: add partition replica available info to support partition table in tiflash

---

README.md

Not a problem.
No code changed. Add a user list in the readme file.
Tests 
- No code

README.md: add a user list

---

model/ddl.go

* model: add schema name, table name to ddl job
* remove table name
cherry-pick https://github.com/pingcap/parser/pull/422

model: add schema name, table name to ddl job (#422)

---

model/ddl.go
model/model_test.go

This is part of PR [TiDB#15540](https://github.com/pingcap/tidb/pull/15540).
Add new ddl action ActionAddColumns for adding multi-columns.
Tests
- Unit test

*: Add new ddl action ActionAddColumns

---

mysql/errcode.go
mysql/errname.go

add tikv stale-command error code.
ref https://github.com/pingcap/tidb/pull/16527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/814)

add stale error code/msg

---

mysql/const.go
parser.y
parser_test.go

Cherry-pick for https://github.com/pingcap/parser/pull/835.

parser: introduce a new privilege for the `set config` statement

---

parser.y

Fix issue #601 
Remove the warning generated for ALTER CHECK, DROP CHECK, CONTSRAINT, CHECK in parser repo, after that we can generate the warning in tidb repo to finish the issue.
Tests 
- No code

ddl: remove warning for constraint and check clause

---

parser.y
parser_test.go

Fix pingcap/tidb#17750.
Remove the empty branch in VariableAssignmentList.
Tests 
- Unit test
Code changes
Side effects

remove the empty branch in VariableAssignmentList

---

parser.y
parser_test.go

Fix pingcap/tidb#17860.
Tests 
- Unit test
Code changes
Side effects

fix charset alias in cast function

---

ast/ddl.go
model/ddl.go
model/model.go
parser.y
parser_test.go

support alter table add/drop/alter constraint
add ddl action type and releated function. 
Tests 
- Unit test
4.0-itai

parser: support alter table add/drop/alter constraint

---

ast/dml.go
parser.y
parser_test.go

parser: support TableOptimizerHints in InsertStmt (#845)

---

model/ddl.go

Cherry-pick https://github.com/pingcap/parser/pull/890

model: correct the usage of json.Unmarshal in DecodeArgs (#890)

---

ast/functions.go
parser_test.go

`tidb_decode_base64` use to decode base64 encoded key
refer issue https://github.com/pingcap/tidb/issues/15951

ast/functions: add tidb_decode_base64 function

---

parser.y

Close #603 (cc #598)
```SQL
ALTER TABLE x REMOVE PARTITIONING;
```
Update judgement in `parser.y`.
Tests 
- Unit test

parser: remove partitioning

---

model/model.go

cherry-pick #952, #947 and #927 to release-4.0
add replica-only state field
add `addingDefinition` field for partitonInfo
Tests 
- Unit test

parser: cherry-pick #952, #947 and #927 to release-4.0

---

parser.y

Solve comment https://github.com/pingcap/parser/pull/961#discussion_r464912950.
Tests
- Unit test

*: fix placement naming

---

terror/terror.go

terror: add stack trace in terror log (#989)

---

yy_parser.go

Close https://github.com/pingcap/parser/issues/959.
As suggested by https://github.com/pingcap/parser/issues/959#issuecomment-668383316.
Enable parse window function by default.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
N/A

yy_parser: enable supportWindowFunc by default

---

ast/dml.go
ast/util.go
ast/util_test.go
misc.go
parser.y
parser_test.go

Part of issue 
https://github.com/pingcap/tidb/issues/19579
Try to support the `wait seconds` grammar in a simple way.
Tests 
- Unit test
Code changes
Side effects

support wait second grammar for select for update

---

docs/quickstart.md

https://github.com/pingcap/parser/issues/812#issuecomment-685674341
Tests 
- Unit test
Code changes
Side effects

quickstart.md: fix typo

---

parser.y

PTAL https://github.com/pingcap/tidb/pull/18968/
and https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_common_test/19053/display/redirect
Tests 
- Unit test
Code changes

parser: fix select field for set operator

---

ast/dml.go
parser.y

PTAL https://github.com/pingcap/tidb/pull/18968
and https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_common_test/19252/display/redirect
Tests 
- Unit test

parser: fix select field for set operator query

---

ast/functions.go
parser_test.go

Support `bin-to-uuid` and `uuid-to-bin` in [pingcap/tidb#20119](https://github.com/pingcap/tidb/issues/20119)
and function const `UUIDToBin` and `BinToUUID`
Tests 
- Unit test
Code changes

expression: Support `bin-to-uuid` and `uuid-to-bin`

---

model/model.go

Signed-off-by: crazycs520 <crazycs520@gmail.com>
cherry-pick https://github.com/pingcap/parser/pull/1042

ddl: support list column partition table

---

model/ddl.go

The comment has explained the thing. Follow details here: https://github.com/pingcap/tidb/pull/20361#discussion_r502578891
Tests 
- Unit test
Code changes

model: add an extra field on Job for passing argumens

---

model/model.go
model/model_test.go

model: add `OriginDefaultValueBit` field to `ColumnInfo` (#904)

---

ast/expressions_test.go
opcode/opcode.go
parser.y
parser_test.go

Fix https://github.com/pingcap/tidb/issues/17791
Tests 
- Unit test
Code changes
Side effects

*: fix not and ! restored

---

ast/misc.go

https://github.com/pingcap/parser/pull/1067 misses some changes for `CreateBindingStmt::Accept` / `DropBindingStmt::Accept`.
Cover the cases for `update` / `delete`.
Tests 
Code changes
N/A
Side effects
N/A
N/A

ast: visit Update / Delete as well for CreateBindingStmt / DropBindingStmt

---

ast/misc.go
ast/misc_test.go

cherry-pick https://github.com/pingcap/parser/pull/1091

ast: fix Restore for INL_HASH_JOIN / INL_MERGE_JOIN hints (#1091)

---

lexer.go
parser_test.go

close https://github.com/pingcap/tidb/issues/21457
add one more look forward.
Tests 
- Unit test
Code changes
- N/A
Side effects
- N/A

spm: fix create binding for update with hint

---

lexer.go
parser_test.go

rt.
Tests 
- Unit test
Code changes
Side effects
- N/A

Manually cherry-pick #1117 to release 4.0

---

digester.go
digester_test.go

cherry-pick https://github.com/pingcap/parser/pull/1128

digester: keep the singleAtIdentifier in normalize (#1128)

---

ast/util.go
ast/util_test.go

Tests 
- Unit test
- No code
Code changes
Side effects

util: Add PrepareStmt into readOnly

---

ast/misc.go
auth/auth.go
misc.go
parser.y
parser_test.go

support GRANT PROXY https://dev.mysql.com/doc/refman/5.7/en/grant.html, mainly to let tidb-tools use parser to check privileges obtained from SHOW GRANTS
Tests 
- Unit test
Code changes
Side effects

*: support GRANT PROXY

---

ast/util.go
ast/util_test.go

Reverts pingcap/parser#1139
Detailed reason at https://github.com/pingcap/parser/pull/1139#issuecomment-752359369

Revert "util: Add PrepareStmt into readOnly"

---

ast/misc.go
misc.go
mysql/const.go
parser.y
parser_test.go
yy_parser.go

close #1143
seems parser can't decide `GRANT aaa, bbb, ccc, ...` before it see `ON` (grant privilege) or `TO` (grant role), so I added structure `RoleOrPriv` and function `convertRoleOrPrivList` to convert it later
Tests 
- Unit test
Code changes
Side effects

*: support dynamic privileges and more extended privileges

---

ast/dml.go
format/format.go

*: add a flag `RestoreWithDefaultDB` for Restore

---

ast/dml.go
parser.y
parser_test.go

Tests 
- Unit test
- No code
Code changes
Side effects

*: support CTE for select statement

---

ast/functions.go
parser_test.go

add a Conditional expression function named `decode_case` 
in oracle it is `decode`, but `deocde` is already use in tidb
Tests 
- Unit test

add decode_case function

---

ast/misc.go
parser_test.go

Parser PR for https://github.com/pingcap/tidb/issues/22663
Add a new format for EXPLAIN.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A

ast: support `explain format = 'test'` syntax

---

README.md

add more resources
add more resources
Tests 
- Unit test
- No code
Code changes
Side effects

README: add more resources

---

ast/misc.go
misc.go
mysql/const.go
parser.y
parser_test.go
yy_parser.go

This ports https://github.com/pingcap/parser/pull/1144 to the 4.0-itai branch.
Tests 
- Unit test
Code changes
Side effects

*: add support for dynamic privileges

---

model/model.go

Add a version for the clustered index
Tests 
- No code
Code changes
Side effects

model: add a version for the clustered index

---

digester.go
digester_test.go

this is the patch of https://github.com/pingcap/parser/pull/1151
Tests 
- Unit test

digest: add missed backquote when getting digest

---

ast/dml.go
parser.y
parser_test.go

https://github.com/pingcap/tidb/issues/23033
Add `ShowStatsExtended` type.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A

parser: support `show stats_extended` syntax

---

format/format.go

Add `RestoreStringWithoutCharset` flag
This is used in [tidb pr](https://github.com/pingcap/tidb/pull/23161)
Tests 
- Unit test
Code changes
Side effects

format: add RestoreStringWithoutCharset flag

---

mysql/const.go

please see https://github.com/pingcap/tidb/issues/23127

privileges: show create view privilege should in `AllTablePrivs`

---

parser.y

add truncate all partition support
remove yacc warning
Tests 
- Unit test

parser: Add truncate all support

---

auth/auth.go
auth/auth_test.go

Cherry-pick https://github.com/pingcap/parser/pull/1197 to branch  4.0
Tests 
- Unit test
- No code
Code changes
Side effects

auth: fix CheckScrambledPassword() panic for invalid input (#1197)

---

mysql/const.go

Needed by [tidb#23519](https://github.com/pingcap/tidb/pull/23519). Tests grant `create_view` will fail due to the missing privs.
Tests 
- Unit test

mysql: add create_view to tables_priv

---

ast/misc.go
parser.y
parser_test.go

The `RENAME USER` statement is added: https://dev.mysql.com/doc/refman/5.7/en/rename-user.html
See above.
Tests 
- Unit test
Code changes
Side effects
- TiDB issue: https://github.com/pingcap/tidb/issues/23648

parser, ast: add RENAME USER stmt

---

ast/expressions.go

https://github.com/pingcap/parser/pull/1195/files#diff-3971773fd5239d32bc6ad60d988968fd0e747b454829a8ee712bbe3e472588beR1226
It is not an equivalent modification. And it makes the test testPlanSuite.TestNameResolver in tidb repo fail.
Tests 
- Unit test
- No code
Code changes
Side effects

ast: fix testPlanSuite.TestNameResolver failed in tidb repo

---

format/format.go

Co-authored-by: ti-srebot <66930949+ti-srebot@users.noreply.github.com>
Cherry-pick #1184 to branch 4.0
Tests 
- Unit test
- No code
Code changes
Side effects

format: add RestoreStringWithoutCharset flag (#1184)

---

ast/dml.go

Signed-off-by: nolouch <nolouch@gmail.com>
`AsOfClause` cannot be visited. 
add it in tablename's `accept`.
Tests 

ast: make AsOf node be accepted

---

ast/dml.go
format/format.go
parser_test.go

Fix #1243
Add a CTENames stack to track CTE.
Tests 
- Unit test
Code changes
Side effects

*: fix cte restore for binding

---

ast/dml.go
format/format.go
parser_test.go

cherry-pick https://github.com/pingcap/parser/pull/1244
Fix #1243
Add a CTENames stack to track CTE.
Tests 
- Unit test
Code changes
Side effects

*: fix cte restore for binding (#1244)

---

ast/misc.go
misc.go
parser.y
parser_test.go

Add support for the help statement
- https://dev.mysql.com/doc/refman/8.0/en/mysql-server-side-help.html
- https://dev.mysql.com/doc/refman/8.0/en/help.html
Tests 
- Unit test
Run the help command in the MySQL client.

Add 'HELP' statement support

---

parser.y
parser_test.go

cherry-pick #1253 to release-5.0

parser: fix the usage of ODBC-styled time literal (#1253)

---

.github/workflows/itcase.yml
.github/workflows/unittest.yml
circle.yml

Signed-off-by: tison <wander4096@gmail.com>
Cherry pick #1247 to release-5.1

.github: migrate ci to GitHub Actions

---

ast/functions.go
misc.go
parser.y

https://github.com/pingcap/tidb/pull/26408
parser implementation
Tests 
- Unit test
Code changes
Side effects

parser: support Oracle translate function

---

ast/ddl.go
ast/ddl_test.go

Add special comment support for index constraints.
Tests 
- Unit test
Code changes
Side effects

add special comments support for index constraints

---

ast/dml.go
parser.y
parser_test.go

Signed-off-by: ailinkid <314806019@qq.com>
solve part of https://github.com/pingcap/tidb/issues/26580
support show create placement policy
Tests 
- Unit test

parser: support show create placement policy

---

ast/dml.go
parser.y
parser_test.go

Support statement 'SHOW PLACEMENT LABELS'
Support statement 'SHOW PLACEMENT LABELS'
Tests 
- Unit test

parser: Support statement 'SHOW PLACEMENT LABELS'

---

charset/charset.go

just sort the charset by its name.
Tests 
- Unit test

charset: sort the charset by its name

---

ast/dml.go
parser.y
parser_test.go

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

parser: fix some parse error for parenthese subqueries (#1255)

---

parser.y

Tests 
Code changes
Side effects

fix select field again

---

ast/base.go

Tests 
- No code
Code changes
- No code changes
Side effects
- No side effects

ast: fix a comment typo

---

mysql/privs.go

Signed-off-by: alfredlu <wslzj40@gmail.com>
Parser related fix for [tidb#28530](https://github.com/pingcap/tidb/issues/28530)
`Create Tmp Table` should be DB level
Tests 
- Unit test
- No code
Code changes
Side effects

Create TMP Tables issue fix

---

mysql/privs.go

Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
ref pingcap/tidb#28531
add references priv in AllColumnPrivs
Tests
- Unit test
Code changes
Side effects

mysql: add references priv in AllColumnPrivs

---

README.md

Tests 
- Unit test
- No code
Code changes
Side effects

Add bytebase/bytebase as a user
