pingcap/parser

- ast/expressions.go
- parser.go
- parser.y
The TiDB PR [8206](https://github.com/pingcap/tidb/pull/8206) requires this PR.
> parser,ast: fix the TiDB issue #8153

- mysql/const.go
This PR updates the SQL Mode to include only_full_group by and no_auto_create_user.
It fixes https://github.com/pingcap/tidb/issues/8129 and partially addresses https://github.com/pingcap/tidb/issues/8128
It depends on: https://github.com/pingcap/tidb/pull/8163
> mysql: Update sql mode default

- ast/expressions.go
Required in the TiDB PR [#8206](https://github.com/pingcap/tidb/pull/8206)
> ast: fix the TiDB issue #8153

- parser_example_test.go
- yy_parser.go
fixes #43
1. add driver import check when create parser, give better panic message.
2. add parser example, so [godoc](https://godoc.org/github/pingcap/parser) will have example just like this 
https://godoc.org/gopkg.in/lysu/parser.v1 after this PR merged
@tiancaiamao
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/44)
> parser: add driver import check & example

- ast/ddl.go
- model/ddl.go
- model/model.go
- parser.go
- parser.y
- parser_test.go
As part of view feature implement, extract create view parameters to CreateViewStmt, ref [pingcap#8416](https://github.com/pingcap/tidb/pull/8416)
> ast, parser: extract create view parameters to CreateViewStmt

- ast/expressions.go
- ast/expressions_test.go
Firstly, we implement `Restore` function of `ast.ColunmNameExpr` and `ast.ColunmName`.
Secondly, we add a test for `Restore`. In this case, `ast.ColunmNameExpr` can't restore to a complete SQL, so we can splice a sql to test it. We have already implemented a test function to simplify our work.
See: [TestExpresionsRestore Function](https://github.com/pingcap/parser/blob/ce4d755a8937ee6bc0e851fafdcd042ab5b1a1c1/ast/expressions_test.go#L122)
> ast: impl Restore of ColunmNameExpr

- ast/misc.go
- parser_test.go
Firstly, we implement `Restore` function of `ast.UseStmt`.
Secondly, we add a test for `Restore`. For `ast.StmtNode`, we can test them in `parser_test.go` because they can restore to a complete SQL. We just need to add expect SQL to `testCase`, the `RunTest` function will help us to test it.
See: [RunTest Function](https://github.com/pingcap/parser/blob/ce4d755a8937ee6bc0e851fafdcd042ab5b1a1c1/parser_test.go#L255)
> ast: implement the Restore function of UseStmt

- charset/charset.go
- mysql/charset.go
- parser.go
- parser.y
- types/field_type.go
cherry-pick from #13 
Require for https://github.com/pingcap/tidb/pull/8590
> *: change default charset from utf8 to utf8mb4 (#13)

- charset/charset.go
- charset/charset_test.go
fix https://github.com/pingcap/tidb/issues/8304
before this PR, below case will failed.:
```
mysql> create table test(id int) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;
ERROR 1115 (42000): Unknown character set: 'UTF8'
```
> charset: make collation case insensitive

- ast/ast.go
- ast/ddl.go
- ast/dml.go
- ast/expressions.go
- ast/functions.go
- ast/misc.go
- ast/stats.go
- ast/util.go
- ast/util_test.go
- go.mod1
- go.sum1
- opcode/opcode.go
- parser_test.go
add RestoreCtx to output in many formats
See: pingcap/tidb#8679
support flags for restore function, we can control the format of output sql text by flags
Update proposal pr: pingcap/tidb#8694
we have to update code(`parser` and `tidb`) at the same time when we change the `Node` interface  because parser and tidb are cyclic dependency.
in order to compile successfully, i have to replace `pingcap/tidb` with `leoppro/tidb` temporarily (and also repale `pingcap/parser` with `leoppro/parser` in tidb).
i will follow this to handle the dependence problem:
1. merge this pr
2. change go.mod of pingcap/tidb#8679, update dependency `pingcap/parser` to master
3. merge pingcap/tidb#8679
4. commit a pr to pingcap/parser,change dependency tidb to master
> parser: add RestoreCtx and change the Node interface

- ast/expressions.go
- ast/expressions_test.go
Implement `Restore` and unit test for `DefaultExpr`.
Issue: https://github.com/pingcap/tidb/issues/8532
> parser: implement Restore for DefaultExpr

- ast/ddl.go
- ast/ddl_test.go
- parser.go
- parser.y
1. implement Restore for IndexOption
2. Add indexOption goyacc code
3. Add indexOptionList goyacc code
---
Issue: [https://github.com/pingcap/tidb/issues/8532](https://github.com/pingcap/tidb/issues/8532)
> parser: implement Restore for IndexOption

- Makefile
- circle.yml
In order to avoid the wrong format submitted by contributors, i add `fmt` command in Makefile to run `gofmt` and it will be execute at `make test` automatically.
> makefile: add fmt command in Makefile

- ast/dml.go
- ast/dml_test.go
- ast/expressions.go
- ast/expressions_test.go
Implement `Restore` and unit tests for `PositionExpr`, `ByItem` and `GroupByClause`.
Issue: https://github.com/pingcap/tidb/issues/8532
> parser: implement Restore for PositionExpr, ByItem and GroupByClause

- ast/dml.go
- ast/dml_test.go
Implement Restore and unit tests for OrderByClause
ps: 
I'm confused about the meaning of field `OrderByClause.ForUnion`.
Does it mean using order by clause in a union query?
> parser: implement Restore for OrderByClause

- model/ddl.go
Part of View feature implement, add drop view action to handle drop view func.
Because most of `DropTable` and `DropView` code logical is the same, so I think we can use `ActionTruncateTablePartition` to pass operation type. and we can use `ActionDropTable` and `ActionDropView` for different logical part.
> add drop view ddl action

- ast/dml.go
- ast/dml_test.go
- ast/util_test.go
- parser.go
- parser.y
Implement `Restore` and unit test for `FrameBound`.
I changed two lines in `parser.y`, though not sure it is completely right.
Issue: https://github.com/pingcap/tidb/issues/8532
> parser: implement Restore for FrameBound

- ast/dml.go
- parser_test.go
Implement `Restore` for `InsertStmt`.
Issue: https://github.com/pingcap/tidb/issues/8532
---
Some test cases are still waiting for #153 .
> parser: implement Restore for InsertStmt

- ast/expressions.go
- ast/expressions_test.go
It's a supplement for my previous PR https://github.com/pingcap/parser/pull/92.
> parser: fix subquery in PatternInExpr.Restore and add tests

- misc.go
Go compiler has a optimize that
```
map[string(b)].. will not cause byte to string allocation
```
So the util/hack here is useless.
Fix https://github.com/pingcap/tidb/pull/9230
remove tidb/util/hack.String
Tests 
- No code
> parser: remove dependency on tidb/util/hack package

- ast/misc.go
- parser_test.go
Minor fix remained of PR #198.
> parser: minor fix of #198

- lexer.go
- lexer_test.go
- parser_test.go
Scan 9eTSs should get an identifier token
Fix https://github.com/pingcap/tidb/issues/8983
Tests 
- Unit test
> parser: fix lexer that treat 9eTSs as a float

- ast/ddl.go
- ast/ddl_test.go
- go.mod1
- mysql/const.go
`STORED` option for generated column is missing after `Restore`
- output `STORED` or `VIRTUAL` based on the `Stored` field of column option.
- fix errors lib introduced in commit https://github.com/pingcap/parser/commit/60fd134cfde20424ba588c785debb3be0a086210
Tests 
- Unit test
> parser: fix stored option in generated column restore

- auth/auth.go
In some test cases, `SessionVars.User` is nil when it is used.
Check if it is nil in its `String()`.
Tests 
- Unit test
Code changes
> auth: use safe String() for UserIdentity

- mysql/const.go
change MySQL version from 5.7.10 to 5.7.25
related PR: 
https://github.com/pingcap/tidb/pull/9553
Side effects
N/A
release-2.1
> mysql: change MySQL version from 5.7.10 to 5.7.25

- charset/charset.go
https://github.com/pingcap/tidb/issues/9635
some of the functions may just return constants. There is no need to do compute every time if we save a map/slice and initialize them. Such as: GetAllCharsets and GetCharsetInfoByID 
1. GetAllCharsets is inited at the init function, and GetAllCharsets can return the inited array directly.
2. GetCharsetInfoByID use a map to fetch Collation effectively, init the map in the init function too.
- Unit test
Code changes
- improve GetAllCharsets and GetCharsetInfoByID
- Need to update go.mod in tidb
> improve: GetAllCharsets and GetCharsetInfoByID

- ast/misc.go
- auth/auth.go
- parser.go
- parser.y
- parser_test.go
add `GrantRoleStmt` to support SQL like `GRANT Roles TO User`.
Add `ast.GrantRoleStmt`
Tests 
- Unit test
Code changes
Side effects
> ast: add GrantRoleStmt to support `GRANT ROLE`

- model/model.go
This is for TiDB PR: https://github.com/pingcap/tidb/pull/9820.
This PR increase table and column version.
Tests 
- No code
> model: increase table and column version

- mysql/errname.go
- parser.go
- parser.y
- parser_test.go
- yy_parser.go
When create table, if year type is not defined correctly, the error message is not consistent with MySQL for now. In MySQL:
```sql
mysql> create table t(f_year year(5))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
ERROR 1818 (HY000): Supports only YEAR or YEAR(4) column.
```
While in TiDB:
```
tidb> create table t(f_year year(5))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for th
e right syntax to use line 1 column 30 near ")ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"Supports only Y
EAR or YEAR(4) column.
```
Return correct error type in parser.
Tests 
- Unit test
- No code
Code …
> parser: fix error message for illegal year type definition.

- types/field_type.go
- types/field_type_test.go
This PR aims to solve the some known show charset/collation issues in TiDB, for example, https://github.com/pingcap/tidb/issues/9837
A `HasCharset` function is ported from MySQL source, for example:
[Field::has_charset()](https://github.com/mysql/mysql-server/blob/3701bd36bec259fe494c75c9b30c57b01e598297/sql/field.h#L1417)
[Field_string::has_charset()](
https://github.com/mysql/mysql-server/blob/3701bd36bec259fe494c75c9b30c57b01e598297/sql/field.h#L3541)
This function can be used in the procedure of some show-schema executions, for example, in MySQL it decides where a given column's `Collation` result is `NULL` in `show full columns` statement:
[sql_show.cc::store_column_type()](https://github.com/mysql/mysql-server/blob/3701bd36bec259fe494c75c9b30c57b01e598297/sql/sql_show.cc#L5303) …
> types: port 'HasCharset' function from MySQL

- ast/misc.go
- parser.go
- parser.y
- parser_test.go
Support revoke roles from users.
Add `RevokeRoleStmt` structure which could parser `REVOKE FROM` SQL. Executor in TiDB will read information from `RevokeRoleStmt` to delete relation from `mysql.role_edges`.
Tests 
- Unit test
Code changes
Side effects
> ast: add revoke role support

- ast/misc.go
- parser.go
- parser.y
- parser_test.go
Support `SET DEFAULT ROLE` to set default active roles for user.
Add `SetDefaultRoleStmt` for `ast` which contain information for `executor` to do next step. 
Tests 
- Unit test
Code changes
Side effects
> ast: add set default role

- model/ddl.go
For some reason the release-2.1 branch never merged commit 20bc24aef58addbd906513ec13424e5755e6d97a, which adds ActionDropView to the model.
tidb-binlog uses the release-2.1 branch to build, and that means it's impossible for it to handle `DROP VIEW` statements.
This branch simply cherry-picks commit 20bc24aef58addbd906513ec13424e5755e6d97a.
Tests 
I checked out the release-2.1 branch of tidb-server and it builds fine after making this change.
> add drop view ddl action (#131)

- digester.go
- digester_test.go
Starting from pingcap/tidb#10284, executing the following would cause TiDB to enter an infinite loop:
```sql
create table `🥳`(a int);
select * from `🥳`;         -- ← this line
```
This is caused by multiple issues:
1. MySQL [does not permit non-BMP characters](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html) like `🥳` in an identifier, no matter quoted or not. But TiDB's and MySQL's behavior differ on such non-BMP characters.
* MySQL allows both unquoted `🥳` and quoted `` `🥳` ``, but both will be translated into a question mark `` `?` ``.
* TiDB treats unquoted `🥳` a lexer error, but accepts the quoted `` `🥳` `` as-is.
2. The `parser.Normalize` strips away the backquotes around the identifier, while MySQL *adds* the backquotes in all cases.
3. Since pingcap/tidb#10284, when we …
> digester: avoid infinite loop when an invalid token is seen

- .gitignore
- README.md
- circle.yml
- test.sh
pingcap/parser doesn't have a coverage report of its own.
Enabled coverage report from `test.sh`.
Created a codecov project at https://codecov.io/gh/pingcap/parser.
Update coverage to codecov after `make test` succeed.
Tests 
- Unit test
Code changes
Side effects
> test: enable coverage when running unit tests

- model/model.go
> model: add MaxShardRowIDBits to table info to record the max ShardRowIDBits be used so far (#252)

- mysql/errcode.go
- mysql/errname.go
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
Add write conflict error for latch and change the error code of ErrTxnTooLarge.
> mysql: add write conflict error for latch and change the error code of ErrTxnTooLarge

- ast/expressions.go
- ast/format_test.go
Fix `caseExpr` format bug.
```
((case when (c0 = 0) then 0 when (c0 > 0) then (c1 / c0) end))
```
before
```
"((CASE WHEN (`c0` = 0) THEN 0WHEN (`c0` > 0) THEN (`c1` / `c0`) END))"
```
now
```
"((CASE WHEN (`c0` = 0) THEN 0 WHEN (`c0` > 0) THEN (`c1` / `c0`) END))"
```
the differents is `THEN 0WHEN` and `THEN 0 WHEN`
Tests 
- Unit test
Code changes
> ast: fix case expression format bug

- ast/ddl.go
Fix panic when create view using prepare.
For https://github.com/pingcap/tidb/pull/10651
> Previously, when we build the create view statement, the Fields of select statement will be rewritten with only name info, so the Expr will be nil when we try to execute the prepare statement, which will cause panic. This PR adds a new field in CreateViewStmt to record the select schema.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
> ast: add new field in create view stmt

- ast/misc.go
relate to https://github.com/pingcap/tidb/pull/10884
just add a field to ExecuteStmt, this field will be runtime used in TiDB 
add a field that hold binary execut args to ExecuteStmt
Tests 
- Unit test
Code changes
- N/A
Side effects
- N/A
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/363)
> add a field that hold binary execut args to ExecuteStmt

- parser.go
- parser.y
- parser_test.go
In this query, `SELECT /*+ MAX_EXECUTION_TIME(1000) */ 1`, the `MAX_EXECUTION_TIME` hint is not saved to `st.TableHints`
https://github.com/pingcap/tidb/issues/10955 is caused by this bug.
Move this line
```
st.TableHints = st.SelectStmtOpts.TableHints
```
to `SelectStmtBasic` will address the problem.
Tests 
- Unit test
> parser: fix hint parsing in `select /*+ max_execution_time */ 1`

- parser.go
- parser.y
- parser_test.go
Cherry-pick from https://github.com/pingcap/parser/pull/366
PTAL @jackysp @kennytm
> parser: fix hint parsing in `select /*+ max_execution_time */ 1` (#366)

- lexer.go
- lexer_test.go
Fix TiDB [issue #10906](https://github.com/pingcap/tidb/issues/10906).
When a SQL statement ends with an invalid part, i.e ` drop table if exists t'xyz`, Scanner's scanString() treat `'xzy` as an incomplete string, and returns `unicode.PlacementChar`.
However, the Lex() incorrectly converts it into a `0`, which means EOF, making it impossible to distinguish from `drop table if exists t`.
So, as long as an invalid token is spotted, the code indicating invalid should be returned.
Tests 
> parser: parse SQL statement to the last character

- mysql/state.go
There is no state for `ErrInvalidJSONPathArrayCell`.
``` mysql
mysql> SELECT JSON_ARRAY_INSERT('[1]', '$.a', 'a');
ERROR 3165 (42000): A path expression is not a path to a cell in an array.
```
> mysql: add a new state `ErrInvalidJSONPathArrayCell`

- test.sh
By default, when testing package A with coverage, only lines in package A will be counted towards the final report, even if the tests called functions from package B.
In this project, however, almost all of our tests are written to `parser_test.go`. Thus even if `parser_test.go` invoked many functions in `ast/*` (package B), those coverages will be lost since `parser_test.go` is outside this directory (in package A).
We changed the default to tell Go to count coverage for all packages regardless of the source. The coverage report should be closer to reality.
It seems like covering all packages in `atomic` mode uses too much RAM for CircleCI when compiling (see attempts 2300, 2302 and 2305 in https://circleci.com/gh/pingcap/parser/tree/pull%2F377), so the test is split into two runs: once …
> test: count coverage for all packages when unit testing

- test.sh
Do not compile tests in parallel, to avoid the compiler OOM inside CircleCI (which has 2 cores + 4 GiB RAM).
Add `-p 1` to limit the number of parallel compiler jobs. 
Merged the two tests back together since there is more space for memory.
Tests 
- Unit test
Code changes
Side effects
> Do not compile unit test in parallel

- ast/util.go
- ast/util_test.go
SQLs like `explain analyze insert into t values (1)` are not read-only, but the `IsReadOnly` function regards them as read-only queries.
Let `IsReadOnly `checks the `Analyze` flag and the internal `Stmt` of `ExplainStmt` to decide if it is `ReadOnly`.
Tests 
- Unit test
> utils: `IsReadOnly` returns wrong result when checking SQLs like `explain analyze insert ...`

- ast/expressions.go
- parser.go
- parser.y
- parser_test.go
Parser part of the cherry-pick for https://github.com/pingcap/tidb/pull/7842
> *: add `Not` flag for `ExistsSubqueryExpr`

- mysql/util.go
- parser.y
- parser_test.go
- types/field_type.go
Related TiDB PR: https://github.com/pingcap/tidb/pull/11443
Support `cast(xxx as double)`.
Mysql support the parser in 8.0.17.
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html
> parser: support cast as double

- ast/ddl.go
- misc.go
- parser.y
- parser_test.go
Add support for TABLE_CHECKSUM. #468 
MySQL syntax:
```
create_table_option:
......
| TABLE_CHECKSUM_SYM opt_equal ulong_num
```
Tests 
- Unit test
> fix: add support for TABLE_CHECKSUM

- goyacc/main.go
- parser.go
- yy_parser.go
Optimizing parser performance
Here is the benchmark, 8%~12% faster than before:
goos: linux
goarch: amd64
Before optimization:
```sh
BenchmarkSysbenchSelect       200000          6121 ns/op        1824 B/op         20 allocs/op
BenchmarkParseComplex          10000        223586 ns/op        61772 B/op        642 allocs/op
BenchmarkParseSimple          100000         19047 ns/op        5144 B/op         71 allocs/op
```
After optimization:
```sh
BenchmarkSysbenchSelect       200000          5586 ns/op        1824 B/op         20 allocs/op
BenchmarkParseComplex          10000        206988 ns/op        61772 B/op        642 allocs/op
BenchmarkParseSimple          100000         16873 ns/op        5144 B/op         71 allocs/op
```
Tests
Unit test
> parser: optimize performance

- ast/expressions.go
cherry pick #27 to release 2.1
> parser, ast: fix the TiDB issue #8153 (#27)

- .github/CODEOWNERS
I added a CODEOWNER rule for this repo, which automatically request the @pingcap/co-parser to review the open PRs.
1. **[done]** installed the [pull assigner](https://github.com/apps/pull-assigner) app for the `pingcap/parser` repo
2. **[done]** created a team named `co-parser` in the `pingcap` account. `co` is short for `codeowner`.
3. create the codeowner rule for this repo, make the codeowner to be `co-parser`
After all these 3 steps, in which this PR is the last step, once a PR in this repo is filed:
1. github automatically request `co-parser` to review that PR
2. pull assigner automatically chose 1, which is configurable, person in that team to review that PR and remove the review request on that team.
Tests 
- No code
> .github: add CODEOWNER rule to request review for PRs automatically

- mysql/const.go
- mysql/const_test.go
for https://github.com/pingcap/tidb/pull/12330
remove GrantPriv from AllGlobalPrivs, AllDBPrivs, AllTablePrivs
> remove GrantPriv from AllGlobalPrivs/AllDBPrivs/AllTablePrivs

- ast/dml.go
- ast/dml_test.go
fix #538. `Restore` method generates incorrect SQL when both table's 'asName' and index hints are present
Tests 
- Unit test
added
Code changes
no
no
no
Side effects
none
special case in `TableSource.Restore` created
no
Closes #538
> ast: fix the bug of TableSource.Restore()

- mysql/errcode.go
- mysql/errname.go
Cherry pick #281 and #334
For https://github.com/pingcap/tidb/pull/12878
> mysql: add write conflict error

- mysql/errcode.go
- mysql/errname.go
Some errors in TiDB do not have an error code. Add parts of them.
Side effects
> mysql: add 2 infoschema related errors for TiDB

- mysql/errcode.go
- mysql/errname.go
Originally, some errors were defined by TiDB and use self-edfined error code, which will show default error code `1105` and make user confused.
Create error code and message related to table. 
Format error message.
Tests 
Code changes
Side effects
> mysql: add error code and message for table related to error

- charset/charset.go
- types/etc.go
- yy_parser.go
following https://github.com/pingcap/tidb/pull/12866 in the parser 
clean up error code and message for the parser in yy_parser.go
remove unnecessary const code define
Tests 
- Unit test
Code changes
- remove code
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/618)
> clean up error code and message for parser

- ast/functions.go
- parser_test.go
> ast/functions: add tidb_decode_plan() function (#557)

- mysql/errcode.go
- mysql/errname.go
> parser: add a mysql error message (#534)

- mysql/errcode.go
- mysql/errname.go
add the missing error code related using in `sysvar.go` in tidb
Tests 
- Unit test
Code changes
Side effects
> sysvar: error code for sysvar.go in tidb

- mysql/errcode.go
- mysql/errname.go
add mysql error `ErrIncorrectType`
> Error number: `3064`; Symbol: `[ER_INCORRECT_TYPE]`; SQLSTATE: `HY000`
Message: Incorrect type for argument %s in function %s.
see https://dev.mysql.com/doc/refman/8.0/en/server-error-reference.html#error_er_incorrect_type
add mysql error `ErrIncorrectType`
Tests 
- None
Code changes
Side effects
- None
- None
> parser: add mysql error `ErrIncorrectType`

- circle.yml
- go.mod1
For the 3.0 branch.
See also https://github.com/pingcap/parser/pull/593
>  *: bump the Go compiler version to 1.13

- mysql/const.go
- mysql/const_test.go
> remove GrantPriv from AllGlobalPrivs/AllDBPrivs/AllTablePrivs (#581)

- mysql/errcode.go
- mysql/errname.go
> mysql: add foreign key error

- mysql/const.go
Originally, user with any global privilege can visit any database, this is not compatible with MySQL.
Add `GlobalDBVisible` to represent subset of privileges which can access any database
Tests 
- Unit test
Code changes
Side effects
> add `GlobalDBVisible` to  represent global privilege which can see all database

- parser.go
- parser.y
Enable to make aggregate function varpop as window function to use. Here is the PR about varpop https://github.com/pingcap/tidb/pull/14101
Tests 
- Unit test
> Add parsing of window function for aggregate function varpop

- Makefile
After merging #679, `cpmod` in Makefile is abandon, it should be removed.
Removing `cpmod` in Makefile.
Tests 
- None
Code changes
- None
Side effects
- None
- None
> Remove abandon command in Makefile

- mysql/errcode.go
- mysql/errname.go
add errcode and errname for variable auto_increment_increment and auto_increment_offset.
Related TiDB PR [#14301](https://github.com/pingcap/tidb/pull/14301)
Tests 
> parser : add invalid auto increment and offset error.

- mysql/errcode.go
- mysql/errname.go
In [#11154](https://github.com/pingcap/tidb/pull/11154), when json_objectagg append json which contains string key and any kinds of value to the result chunk, the value type can be any types but appendBinary only support few types, so many types will not supported now in json_objectagg result and I add the error code for this.
> add json_objetagg's unsupported second argument type errorcode

- model/model.go
Now the default value in `columnInfo` has been evaluated.
but in some cases, the default value is dynamic, needing to be evaluated every time call it.
It's a little bit like a generated column, so we store the expression restored string in default value.
So we need a field to judge the default string is whether the `common_string` or `expr_string`.
after this pr:
```
create sequence seq
create table t(a int default next value for seq)
```
the `a`'s default value will be a string equal to `"nextval(seq)"`
the  field `DefaultIsExpr` in columnInfo of `a` will be true.
linked TiDB PR:
Tests 
Code changes
- Has added fields in columnInfo
> parser: support expression restored string in default value.

- terror/terror.go
- terror/terror_test.go
- yy_parser.go
make terror support register new error code and error msg and prepare for move error code/msg out of parser
Tests 
- Unit test
Code changes
- impl
Side effects
- n/a
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/734)
>  support register new terror

- mysql/errcode.go
- mysql/errname.go
add errcode and errname for unsupported sequence default value for column type
such as:
```
create sequence seq;
create table t(a char(1) default next value for seq);
result: 
this 2 SQL will execute success even in MariaDB, but we wanna check this.
```
Tests 
> parser: add errcode and errname of unsupported sequence default value for column type

- ast/functions.go
- ast/functions_test.go
- misc.go
- parser.y
This PR is the implementation of `WEIGHT_STRING()` in parser, you can check the [MySQL manual](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_weight-string) for more details.
Here we only implement a part of the full syntax: `WEIGHT_STRING(str [AS {CHAR|BINARY}(N)])`, according to MySQL manual:
> WEIGHT_STRING() is a debugging function intended for internal use. Its behavior can change without notice between MySQL versions. It can be used for testing and debugging of collations, especially if you are adding a new collation. 
We can adjust this function on our own needs.
Related issue: https://github.com/pingcap/tidb/issues/3580
Related TiDB PR: https://github.com/pingcap/tidb/pull/14792
Add `WEIGHT_STRING()` in parser.
Tests 
Code changes
- Has …
> parser: add WEIGHT_STRING() function

- model/model.go
- model/model_test.go
Remove ColumnToProto() function and do not rewrite the collation ID, since new collations are supported by TiDB now.
As stated above.
Tests 
- Unit test
Code changes
Side effects
- NA
> model: do not rewrite collation id as default for tipb.

- ast/util.go
- ast/util_test.go
Fix https://github.com/pingcap/tidb/issues/15050.
`UNION` statement and `SHOW` statement are not treated as readonly statement. These statements are executed again in retrying transactions.
Set `UnionStmt` and `ShowStmt` as readonly.
Tests 
- Unit test
Code changes
Side effects
N/A
Release Note
- Treat `UNION` statement and `SHOW` statement as readonly statements.
> parser: set `UnionStmt` and `ShowStmt` as readonly

- ast/util.go
- ast/util_test.go
Conflicting files:
util.go
util_test.go
Fix https://github.com/pingcap/tidb/issues/15050.
`UNION` statement and `SHOW` statement are not treated as readonly statement. These statements are executed again in retrying transactions.
Set `UnionStmt` and `ShowStmt` as readonly.
Tests 
- Unit test
Code changes
Side effects
N/A
Release Note
- Treat `UNION` statement and `SHOW` statement as readonly statements.
> parser: set `UnionStmt` and `ShowStmt` as readonly (#755)

- ast/expressions.go
- ast/expressions_test.go
- ast/functions_test.go
- ast/misc_test.go
- parser.go
- parser.y
- test_driver/test_driver.go
- test_driver/test_driver_datum.go
set charset and collate for string literal correctly
In `NewValueExpr`, set the charset and collate for string literal.
The charset and collate are from parser, which is the connection charset and connection collation.
See also https://dev.mysql.com/doc/refman/8.0/en/charset-literal.html
Tests 
- No code
Tests are added in TiDB, need to merge together.
Code changes
Side effects
> *: set charset and collate for string literals correctly

- mysql/errcode.go
- mysql/errname.go
cherry-pick #779 to 3.1
no conflict
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/780)
> add require secure transport error (#779)

- model/ddl.go
- model/model_test.go
This is part of PR [tidb#15540](https://github.com/pingcap/tidb/pull/15540).
Since we have add `ActionAddColumns`, when `ActionAddColumns` job is rolling back,we need drop multi-columns. See details https://github.com/pingcap/tidb/pull/15540#discussion_r396951762
Add new action ActionDropColumns
Tests
- Unit test
> *: add new action ActionDropColumns

- digester_test.go
- lexer.go
There's a bug in normalizing SQL. '/' is not shown in normalized SQL.
Normalize `select 1 / 2`.
Before:  `select ? ?`
After: `select ? / ?`
`lit` is not set when scanning '/'. Now it's set.
Tests 
- Unit test
Code changes
N/A
Side effects
Release Note
- Fix the bug that '/' is not shown in the normalized SQL.
- Compatibility problem: Digests in slow log is not matched after upgrading TiDB.
> digest: fix '/' in normalizing SQL

- ast/expressions.go
- ast/expressions_test.go
- opcode/opcode.go
- opcode/opcode_test.go
It was found that in pingcap/tidb#15948 the Restore() involving the `DIV` operator was incorrect: `4 DIV 2` by default was restored without spaces as `4DIV2`.
Here we refactored the `opcode` module to include whether the operator is a keyword. Spaces around keyword-like ops are enforced.
Tests 
- Unit test
Code changes
* I don't know why the map `opcode.Ops` was exported. It is used nowhere. This PR makes it private.
Side effects
* needs to cherry-pick to all previous releases.
> opcode,ast: fix invalid restore of '4 DIV 2' (became '4DIV2')

- types/field_type.go
- types/field_type_test.go
This pr is a subsequent modification of [parser/pull/832](https://github.com/pingcap/parser/pull/832).
We find that when `Decimal` is specified, `Flen` will have a specific effect, see [floating-point-types](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html).
Current judgments can also cause problems.
This pr fixes it.
Tests 
Code changes
> types: Update `FieldType.Equal` safety.

- ast/ddl.go
- model/ddl.go
- parser.go
- parser.y
For support `alter table ... alter index ... invisible` statement, we add a new DDL action `AlterIndexVisibility`.
Tests 
- Unit test
Code changes
Side effects
- None
- None
> parser: add new ddl action AlterIndexVisibility

- ast/functions.go
- ast/functions_test.go
- parser.go
- parser.y
- parser_test.go
Cherry-pick https://github.com/pingcap/parser/pull/813
---
part of https://github.com/pingcap/tidb/issues/6838
Tests 
- Unit test
Code changes
Side effects
- None
> parser: add order by clause in group_concat (#813)

- model/model.go
To support clustered index.
https://github.com/pingcap/tidb/pull/17044
> model: add IsCommonHandle field on TableInfo

- parser.y
- parser_test.go
Signed-off-by: crazycs520 <crazycs520@gmail.com>
As the title said.
here is an example: 
```sql
mysql>show table t partition (p4) regions;
+-----------+----------------+----------------+-----------+-----------------+-------+------------+---------------+------------+----------------------+------------------+
| REGION_ID | START_KEY      | END_KEY        | LEADER_ID | LEADER_STORE_ID | PEERS | SCATTERING | WRITTEN_BYTES | READ_BYTES | APPROXIMATE_SIZE(MB) | APPROXIMATE_KEYS |
+-----------+----------------+----------------+-----------+-----------------+-------+------------+---------------+------------+----------------------+------------------+
| 1047      | t_154_r        | t_154_r_200000 | 1048      | 1               | 1048  | 0          | 0             | 0          | 1                    | …
```
> support show table partition regions

- parser.y
- parser_test.go
Pick for https://github.com/pingcap/parser/pull/821.
> parser: support using dash('-') in config item names 

- parser.y
- parser_test.go
Support `delete from t partition (p0,p1)` ...
update parser.y
Tests 
- Unit test
> parser: support partition selection grammer for the delete statement

- model/ddl.go
Fixed #889
> decoding into []json.RawMessage, so you can then decode each into the appropriate type in a second pass
Using `json.Decoder` is more complex.
```go
if len(job.RawArgs) == 0 {
return nil
}
decoder := json.NewDecoder(bytes.NewReader(job.RawArgs))
token, err := decoder.Token()
if err != nil {
return errors.Trace(err)
}
if del, ok := token.(json.Delim); !ok || del != '[' {
return nil
}
var i int
for decoder.More() {
if i == len(args) {
break
}
if err := decoder.Decode(args[i]); err != nil {
return errors.Trace(err)
}
i++
}
job.Args = args[:i]
return nil
```
Tests 
- Run TiDB's unit-test with Go 1.15 
Side effects
> model: correct the usage of json.Unmarshal in DecodeArgs

- model/ddl.go
Cherry-pick https://github.com/pingcap/parser/pull/890
> model: correct the usage of json.Unmarshal in DecodeArgs (#890)

- model/model.go
- model/model_test.go
Related to pingcap/tidb#18036
Add `OriginDefaultValueBit` field to `ColumnInfo`.
Tests 
- Unit test
Code changes
Side effects
> model: add `OriginDefaultValueBit` field to `ColumnInfo`

- ast/misc.go
- parser.y
- parser_test.go
`set charset` statement is not equal to `set names` statement, we need to distinguish them.
Related TiDB [PR](https://github.com/pingcap/tidb/pull/16984).
If the statement is `set charset`, we use `SetCharset` instead of `SetNames` to mark it.
Tests 
- Unit test
Code changes
Side effects
> Fix `set charset` statement

- parser.y
fix: remove warning in parser for rebuild/check/optimize/repair partition
Signed-off-by: Wang Ruichao <wangruichao2014@xiaochuankeji.cn>
Fix #604 .
On one hand: remove warning in `pingcap/parser` repo;
on the other hand: add warning for `AlterTableRebuildPartition`, `AlterTableCheckPartitions`, `AlterTableOptimizePartition`, `AlterTableRepairPartition` in ddl module in `pingcap/tidb` repo.
Tests 
- Unit test
> fix: remove warning in parser for rebuild partition, etc

- parser_test.go
- types/field_type.go
https://github.com/pingcap/tidb/issues/18148
Before this PR:
`SELECT CAST(data AS BINARY)` will be restored to ``SELECT CAST(`data` AS BINARY BINARY)``
Tests 
- Unit test
Code changes
Side effects
> types: fix restore cast as binary

- parser_test.go
- types/field_type.go
https://github.com/pingcap/tidb/issues/18148
Before this PR:
`SELECT CAST(data AS BINARY)` will be restored to ``SELECT CAST(`data` AS BINARY BINARY)``
Tests 
- Unit test
Code changes
Side effects
> types: fix restore cast as binary (#922)

- parser.y
- types/field_type.go
Signed-off-by: AilinKid <314806019@qq.com>
Since TiDB and Parser has implemented much tests with int(11), bigint(20) and so on, it better to add the varible as a transition from `supported` to `deprecated`.
The benefit is that we don't have to change all the tests implemented with int(11) ,bigint(20) and so on, even some tests in the other repo, like TiDB-Test, Parser...
Also
TiDB [#18787](https://github.com/pingcap/tidb/pull/18787) is the pr to fix the integration test (removing the mysql.decimal field), but it's parser is including max-display-length-warning commit which I filed serveral days ago, which will cause test check failed in TiDB Repo.
So this pr is to correct the TiDB test check behavior.
Add the config variable in parser drived by TiDB config.
Tests 
- Unit test
- …
> parser: add config variable to control max display length

- docs/quickstart.md
Using a version tag to `go get` the dependency is not the correct way. 
```console
go get github.com/pingcap/parser@v4.0.0-rc.1: github.com/pingcap/parser@v4.0.0-rc.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```
Under ideal circumstances, the path should be something like 
```
github.com/pingcap/parser/v4@master
``` 
when the new major version is not backward compatible. However, this is still under discussion due to potential compatibility problems.
As a workaround, we can specify the git hash manually.
See the changes.
Tests 
N/A
Code changes
N/A
Side effects
N/A
N/A
> quickstart.md: get dependency with git hash instead of version tag

- model/model.go
Signed-off-by: AilinKid <314806019@qq.com>
The new added replica-only state should strictly be appended to the last one.
Otherwise, it will cause a rolling-update failure.
Referring issue: https://github.com/pingcap/tidb/issues/18873
append replica-only state to previous one strictly
Tests 
```
Manual test like what the issue described:
1: starting a TiDB (v4.0.0) server.
2: rolling update it to the TiDB master (commit 4170007fb60f3ad1ebb11027bbb6ac97c408929d).
3: checking this process without any error mentioned in the issue above.
```
> parser: append replica-only state to previous one strictly

- parser.y
- types/field_type_test.go
Related to https://github.com/pingcap/tidb/issues/18870.
Correct calculation of field lengths for Enum and Set types
Now, when creating tables, field lengths for Enum and Set type columns are set to -1, which is not correct.
This PR fixes their field length as rules below:
1. enum_flen = max(element_flen)
2. set_flen = sum(element_flen) + number_of_elements - 1
These rules are from MySQL.
Tests 
- Unit test
> correct calculation of field lengths for Enum and Set types

- model/model.go
In `StateReplicaOnly` schema state, we see the log is `SchemaState:none`.
Add replica only type to `String`.
Tests 
> model: add StateReplicaOnly type to string

- model/model.go
- model/model_test.go
In PR pingcap/tidb#18036,
```sql
drop table if exists t;
create table t (a bit);
insert into t values (null);
select count(*) from t where a is null;
```
Expected: 
```
+----------+
| count(*) |
+----------+
| 1        |
+----------+
```
But got:
```
+----------+
| count(*) |
+----------+
| 0        |
+----------+
```
If the origin default value in the BIT column is null, it should not be converted to a string. 
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
> model: fix null origin default value for bit column

- misc.go
- parser.y
- parser_test.go
#973
not close it because only a part of the syntax is supported.
Support `FETCH { FIRST | NEXT } [ n ] { ROW | ROWS } ONLY` syntax.
Note1: 
MS SQL Server/Oracle/PostgreSQL support `[ OFFSET m { ROW | ROWS } ] FETCH { FIRST | NEXT } [ n ] { ROW | ROWS } ONLY` syntax. We didn't implement the `[ OFFSET m { ROW | ROWS } ]` part.
That's because `offset` is not a reserved word in MySQL(which is we need to be compatible with) so SQLs like `select * from t offset` and `select 1 offset` are valid. Supporting this syntax means we need to handle those SQLs and SQLs like `select a from t offset offset 3 rows fetch first 2 rows only` correctly. 
I'm not sure why yacc can't resolve this automatically but simply adding a rule for `[ OFFSET m { ROW | ROWS } ]` would cause syntax conflicts. Supporting …
> parser: add `FETCH FIRST` syntax support

- terror/terror.go
- None
`terror.Log` can print stack trace for better debugging terror logs like https://asktug.com/t/topic/36843
```
$ go test -check.f TestLog
[2020/08/28 16:23:23.840 +08:00] [ERROR] [terror.go:375] ["encountered error"] [error="xxx\ngithub.com/pingcap/errors.AddStack\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15\ngithub.com/pingcap/parser/terror.Log\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror.go:375\ngithub.com/pingcap/parser/terror.(*testTErrorSuite).TestLog\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror_test.go:167\nreflect.Value.call\n\t/usr/local/Cellar/go@1.13/1.13.9/lib …
```
> terror: add stack trace in terror log

- ast/format_test.go
- ast/functions.go
- parser.y
- types/field_type.go
- yy_parser.go
The charset and collation of `cast function` are not correct.
Tests 
- No code
Will be added in TiDB later.
Code changes
Side effects
> fix tiny bug about cast function

- lexer.go
- parser_test.go
close #987 
Added a look back token to filter out special case `FOR UPDATE` which might mistakenly take the comment after as a optimization hint.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
> Fix syntax error caused by unexpected hint

- ast/stats.go
- misc.go
- parser.y
- parser_test.go
Signed-off-by: Wang Ruichao <wangruichao2014@xiaochuankeji.cn>
Close #361 , cc https://github.com/pingcap/tidb/issues/14800
```SQL
ANALYZE TABLE `t1` UPDATE HISTOGRAM ON `b` WITH 1024 BUCKETS;
```
Add "ALTER TABLE... UPDATE/DROP HISTOGRAM" in parser.y, according to the document of mysql: https://dev.mysql.com/doc/refman/8.0/en/analyze-table.html
Tests 
- Unit test
> feat: add "HISTOGRAM" option in "ALTER TABLE... UPDATE/DROP..."

- parser.y
- parser_test.go
https://github.com/pingcap/tidb/issues/18949
PR in tidb https://github.com/pingcap/tidb/pull/19612
Trailing spaces are automatically deleted from ENUM member values in the table definition when a table is created
see https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-literals
see https://dev.mysql.com/doc/refman/8.0/en/set.html
Tests 
- Unit test
- No code
> parser: trim trailing spaces in enum and set

- ast/expressions.go
Reverts pingcap/parser#1007 since the corresponding TiDB https://github.com/pingcap/tidb/pull/19869 is not ready now.
> Revert "ast: Change the implementation of Accept for DefaultExpr"

- parser_test.go
- yy_parser.go
Refer to https://github.com/pingcap/tidb/issues/17791.
Set SQL mode to the default mode.
Tests 
- Unit test
Code changes
Side effects
> yy_parser: use the default SQL mode when create a new parser.

- mysql/const.go
Tidb does not start properly with error `[error="[privilege:8049]mysql.user"]`.
Adjust the order of CreateTablespacePriv.
Tests
> fix CreateTablespacePriv order in const

- ast/ddl.go
- misc.go
- parser.y
- parser_test.go
Signed-off-by: AilinKid <314806019@qq.com>
Try to support `alter sequence`.
The syntax here is compatible with oracle, the additional `restart` syntax is borrowed from MariaDB which could reset a sequence quickly when altering a sequence rather than dropping it and creating a new one.
Tests 
- Unit test
> parser: support alter sequence

- ast/ddl.go
- ast/ddl_test.go
it's optional to write a comma between `table_option`
https://dev.mysql.com/doc/refman/5.7/en/alter-table.html
if we write it default, a single schema change DDL will become multi-schema change DDL as in https://github.com/pingcap/dm/issues/1175#issuecomment-709900540
don't write comma
Tests 
- Unit test
Code changes
Side effects
- Breaking backward compatibility (?)
> ast: Don't write comma when restore TableOption of ALTER TABLE

- model/model.go
- model/model_test.go
Cherry-pick #983 to release-4.0.
> model: fix null origin default value for bit column (#983)

- model/model.go
- model/model_test.go
Cherry-pick #904 to release-3.0.
> model: add `OriginDefaultValueBit` field to `ColumnInfo` (#904)

- parser.y
- parser_test.go
Cherry-pick #968 to release-4.0.
> parser.y: allow subquery without table alias syntax-checked (#968)

- model/model.go
Signed-off-by: crazycs520 <crazycs520@gmail.com>
Optimize for `runtime.duffcopy`:
Here is a benchmark test:
```go
func (pi *PartitionInfo) GetNameByID(id int64) string {
definitions := pi.Definitions
for i := range definitions {
if id == definitions[i].ID {
return definitions[i].Name.L
}
}
return ""
}
func (pi *PartitionInfo) GetNameByIDOrigin(id int64) string {
for _, def := range pi.Definitions {
if id == def.ID {
return def.Name.L
}
}
return ""
}
func BenchmarkGetNameByID(b *testing.B) {
pi := &PartitionInfo{}
pi.Definitions = make([]PartitionDefinition, 0, 10000)
for i := 0; i < 10000; i++ {
pi.Definitions = append(pi.Definitions, PartitionDefinition{ID: int64(i), Name: NewCIStr(strconv.Itoa(i))})
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
pi.GetNameByID(int64(i % 10001))
}
}
func …
```
> *: tiny optimize for huge partition table

- model/model.go
cherry-pick https://github.com/pingcap/parser/pull/1072
Signed-off-by: crazycs520 <crazycs520@gmail.com>
Optimize for `runtime.duffcopy`:
Here is a benchmark test:
```go
func (pi *PartitionInfo) GetNameByID(id int64) string {
definitions := pi.Definitions
for i := range definitions {
if id == definitions[i].ID {
return definitions[i].Name.L
}
}
return ""
}
func (pi *PartitionInfo) GetNameByIDOrigin(id int64) string {
for _, def := range pi.Definitions {
if id == def.ID {
return def.Name.L
}
}
return ""
}
func BenchmarkGetNameByID(b *testing.B) {
pi := &PartitionInfo{}
pi.Definitions = make([]PartitionDefinition, 0, 10000)
for i := 0; i < 10000; i++ {
pi.Definitions = append(pi.Definitions, PartitionDefinition{ID: int64(i), Name: NewCIStr(strconv.Itoa(i))})
}
b.ResetTimer()
for i := 0; i < …
```
> *: tiny optimize for huge partition table (#1072)

- ast/misc.go
- ast/misc_test.go
Currently, hint `INL_HASH_JOIN(t1,t2)` would be restored as `INL_HASH_JOIN()`, which would cause `explain format = 'hint'` or baseline capture broken.
Restore table parameters for these 2 kinds of hints.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
> ast: fix Restore for INL_HASH_JOIN / INL_MERGE_JOIN hints

- ast/ddl.go
- model/model.go
- parser.y
- parser_test.go
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
This PR intends to support Oracle like `alter table read only/write` syntax. It is used to do not release locks automatically when the session exits. Which will make the memory cache easy to effect. Related to https://github.com/pingcap/tidb/pull/20396
Tests 
- Unit test
> *: add alter table read only/write support

- mysql/util.go
For https://github.com/pingcap/tidb/issues/11327
Tests 
- No code
Code changes
Side effects
> mysql: fix wrong default decimal length

- digester.go
- digester_test.go
cherry-pick #1040 to release-4.0
---
https://github.com/pingcap/tidb/issues/19836
Currently, `normalize()` doesn't handle `paramMarker`('?'), this makes some bindings can't work as expected like the issue above.
Prepared statement `select * from t limit ?, ?` is normalized to `select * from t limit ?, ?`. However, a binding for `select * from t limit 1, 2` is normalized to and can only be matched by `select * from t limit ...`.
When normalizing SQL, consider `paramMarker` as literal, this will make `paramMarker` be normalized to `genericSymbol`. This makes sense also because both `paramMarker` and `genericSymbol` correspond to '?'.
After this change, `select * from t limit ?, ?` will be normalized to `select * from t limit ...` instead of `select * from t limit ?, ?`.
Tests 
- Unit test
> digester: consider paramMarker as literal when normalizing SQL (#1040)

- types/field_type.go
- types/field_type_test.go
Close https://github.com/pingcap/tidb/issues/17332
If displayFlen is 0, don't use the default value.
Tests 
- Unit test
Code changes
Side effects
> types: fix incorrect `show create table` when the flen is 0 for char and varchar

- parser.y
pingcap/tidb#21486. 
Initialize the `SelectStmt.Fields` fields with `*` so TiDB code using `sel.Fields.Fields` won't panic.
Tests 
* `TABLE t` works after using the new parser.
Code changes
Side effects
> parser.y: populate the Fields field for TABLE and VALUES statements

- ast/dml.go
- ast/misc.go
- parser.y
- parser_test.go
- yy_parser.go
Close issue https://github.com/pingcap/tidb/issues/20133
Add SelectStmtOptsList, and merge options if there is more than one option.
Note: After this PR merge.
`select SQL_BUFFER_RESULT SQL_BUFFER_RESULT  from t;` would cause parser error. This is the same as MySQL.
Tests 
- Unit test
Code changes
Side effects
> *: support multiple select options

- ast/functions.go
- ast/functions_test.go
cherry-pick https://github.com/pingcap/parser/pull/1124
> ast: fix restore panic for TRIM() when arguments contain column name (#1124)

- digester.go
- digester_test.go
Fix https://github.com/pingcap/tidb/issues/21820
Keep the `@` when normalizing a query.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
> digester: keep the singleAtIdentifier in normalize

- lexer.go
- lexer_test.go
- parser_test.go
close https://github.com/pingcap/parser/issues/1114
related tidb issues: 
https://github.com/pingcap/tidb/issues/3963
https://github.com/pingcap/tidb/issues/21677
`dot` after the identifier is token '.'
start with `dot` should be numbers
Tests 
- Unit test
> lexer: treat dot differently in different context

- ast/misc.go
- parser.y
- parser_test.go
parser didn't support `GRANT ... ON FUNCTION ...`, where DM plans to parse and check privileges in https://github.com/pingcap/dm/issues/1320
ref https://dev.mysql.com/doc/refman/5.7/en/grant.html
add `ObjectTypeFunction` and `ObjectTypeProcedure`
Tests 
- Unit test
Code changes
Side effects
> ast, parser: add FUNCTION and PROCEDURE for GRANT object_type

- parser.y
- parser_test.go
syntax like `select .t.a from t` is invalid in MySQL. remove it
> parser: remove invalid syntax

- parser.y
- parser_test.go
To Compatible with mysql8 syntax. Fix pingcap/tidb#14297
Add WhereClauseOptional in SelectStmt block  in parser.y
Tests 
- Unit test
```
MySQL [test]> select 1 where 1=1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
MySQL [test]>
```
Code changes
- N/A
Side effects
- N/A
> parser: Compatible with mysql8 fix select 1 where 1=1

- yy_parser.go
Cherry-pick #986 to release-4.0.
Close https://github.com/pingcap/tidb/issues/22151.
> yy_parser: enable supportWindowFunc by default (#986)

- ast/ddl.go
- ast/ddl_test.go
- ast/misc.go
- misc.go
- parser.y
- parser_test.go
Change the extended statistics SQL interfaces according to https://docs.google.com/document/d/1rRIQ8ekoKJH8qeB-J15QRaycLys8_19GBnij7q_O7Vg/edit.
Use `ALTER TABLE ... ADD / DROP STATISTICS` syntax for create / drop extended statistics. Old syntax in https://github.com/pingcap/parser/pull/913 would be removed later once the new syntax support is finished.
Tests 
- Unit test
Code changes
Side effects
- Breaking backward compatibility: the old syntax is not generally available now, so it should be fine to be removed.
N/A
> *: create / drop extended stats by ALTER TABLE

- parser.y
- parser_test.go
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
Remove `PROXY` from reserved keyword mapping because in MySQL it's not a reserved keyword.
Tests 
- Unit test
> *: remove proxy from reserved keyword

- README.md
CONTRIBUTING.md was moved and the link to it in README.md is broken.
Related PR: https://github.com/pingcap/tidb/pull/20964
Just replace the broken link in README.
Tests 
- No code
> parser: update the broken link for Contribution Guide in README.md

- model/model.go
Issue: https://github.com/pingcap/tidb/issues/982
TiDB PR: https://github.com/pingcap/tidb/pull/20708
Tests 
- Unit test
Code changes
Side effects
N/A
> model: add a new TableInfoVersion for separating id allocators

- ast/dml.go
- ast/dml_test.go
- format/format.go
- parser_test.go
```sql
ts = TableSource
select * from (t1) join t2;
select * from t1, t2;              select * from t1 join t2;
join                                    join
/  \                                    /  \
join  ts                                 ts  ts
|
ts
select * from t1 join (t2);      select * from (t1) join (t2);
join                                  join
/  \                                  /  \
ts  join                             join join
|                               |     |
ts                               ts    ts
```
there are 4 kinds of `join` AST, and SQL `select * from t1, t2; ` will restore to `select * from (t1) join t2;`. 
it is fine if `t1` is `TableName` or `Join`, but if `t1` is a `select` stmt, it will generate SQL like 
```sql
select * from (select * from t) t1, …
```
> restore: fix the bug about restore join table generate syntax error SQL

- ast/stats.go
- parser.y
- parser_test.go
statistics: add a new syntax to support dropping statistics of partitions
statistics: add a new syntax to support dropping statistics of partitions
Tests 
- Unit test
> statistics: add a new syntax to support dropping statistics of partitions

- ast/stats.go
- parser.y
- parser_test.go
Before this PR, we already have the syntax `drop stats {table-name} partition {partition-name}` to drop partition-stats.
And if we want to drop global-stats, we now use the keyword `global` to replace `{partition-name}` like `drop stats t partition global`.
But this solution may cause a conflict if a user names a partition as `global`.
To solve this conflict, this PR introduces a new kind of syntax `drop stats {table-name} global`.
Tests 
- Unit test
> statistics: introduce a new kind of syntax to drop global-stats

- digester.go
- digester_test.go
Currently, `Normalize()` converts `SELECT NULL` to `select null`, while NULL is regarded as a literal in MySQL, as described in the [documentation](https://dev.mysql.com/doc/refman/8.0/en/literals.html). It seems natural that `SELECT NULL` would be converted to `select ?` from the consistency viewpoint.
A famous query normalization tool, [pt-fingerprint](https://www.percona.com/doc/percona-toolkit/LATEST/pt-fingerprint.html), for MySQL also treats NULL in that way.
```
$ pt-fingerprint --query "SELECT NULL"
select ?
```
Let `isLit()` regards `NULL` and `\N` as a literal.
Note that checking if `tok == null` in `isLit()` is not enough because `scan()` recognize `\N` as `null` but `NULL` as `identifier`. We should also check if `strings.ToLower(t.lit) == "null"`. This seems not so strange, …
> parser: regard NULL as literal when normalizing query

- model/model.go
- model/model_test.go
fix https://github.com/pingcap/tics/issues/1509, where the extra PK 's not null flag is not right set.
set the not null flag for extran PK
Tests 
- Unit test
https://github.com/pingcap/tidb/pull/23237
Side effects
> set right not null flag when newing extra PK

- go.mod
- go.sum
https://github.com/pingcap/parser/pull/851 introduce go-sql-driver/mysql dependence with high version for test case
but https://github.com/pingcap/mysql-tester will use pingcap/parser
and https://github.com/go-sql-driver/mysql/pull/676 remove Warn API and strict mode which heavy used in pingcap/mysql-tester and pingcap/tidb-test.
(warn can workaround but strict need modify large number for tidb-test testcase)
so this PR choose downgrade mysql/driver version
downgrade veresion
Tests 
- Manual test 
```
upgrade mysql-tester and run tidb-test success
```
Code changes
- n/a
Side effects
- n/a
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/parser/1193)
> downgrade mysql driver version

- auth/auth.go
- auth/auth_test.go
The input data may be invalid, but calling `CheckScrambledPassword()` on malformed data should not make TiDB server panic.
Tests 
- Unit test
> auth: fix CheckScrambledPassword() panic for invalid input

- ast/misc.go
- misc.go
- parser.y
- parser_test.go
Implements https://github.com/pingcap/parser/pull/1154 for release-4.0 branch.
A new `FLUSH CLIENT_ERRORS_SUMMARY` statement is added.
The corresponding PR in TiDB is https://github.com/pingcap/tidb/pull/23267
Tests 
- Unit test
Code changes
Side effects
-  PR against master: https://github.com/pingcap/parser/pull/1154
- TiDB PR: https://github.com/pingcap/tidb/pull/23267
> *: Add flush client_errors_summary for 4.0

- ast/misc.go
- parser.y
- parser_test.go
As part of change column type (but also other operations) it is difficult to know what happens when a DDL operation is performed. MySQL supports explain assertions, but these are a little limited.
In chatting to @bb7133 we discussed adding an `EXPLAIN` for DDL.  The TiDB issue is https://github.com/pingcap/tidb/issues/8429
This is an extension to MySQL syntax.
Alter table statements are now explainable.
Tests 
- Unit test
Code changes
Side effects
- None
> parser, ast: add explain for ALTER TABLE stmts

- ast/format_test.go
- mysql/util.go
Fix https://github.com/pingcap/tidb/issues/23495 in TiDB
modify TypeNewDecimal length in defaultLengthAndDecimalForCast from 11 to 10. 
Tests 
- Unit test
> mysql: modify TypeNewDecimal length in defaultLengthAndDecimalForCast

- ast/dml.go
`ast.Join.Accept` should visit its field `Using`
A for loop is added to `ast.Join.Accept` for visiting all nodes in the slice `Using`
Tests 
`make test` passes in repo `pingcap/tidb` while replace `pingcap/parser` to `pragmatwice/parser@patch-ast-dml-join-accept`
```
...
Great, all tests passed.
```
Code changes
Side effects
> ast: visit Join.Using in Join.Accept

- model/ddl.go
- model/model.go
- model/model_test.go
- https://github.com/pingcap/tidb/issues/23494
Tests 
Code changes
> ddl: admin show ddl jobs output confusing with multiple jobs

- ast/ddl.go
- misc.go
- model/model.go
- parser.y
- parser_test.go
Support `create global temporary table ... on commit delete rows`
See https://github.com/pingcap/tidb/pull/24168
This syntax is compatible with MySQL temporary table, a `GLOBAL` keyword is used to distinguish them.
This syntax is much the same with Oracle (and also  the ANSI SQL standard).
A compatibility issue is that when a user use this syntax and use a downstream MySQL as TiDB backup, they will encounter DDL error when the use this statement, because this syntax is a superset of the MySQL syntax.
In the real use cases, it shouldn't be a problem, because if a user use this syntax, they probably migrating from Oracle, so they do not use a MySQL backup.
Tests 
- Unit test
Code changes
> parser: support the 'create global temporary table' syntax

- ast/dml.go
- parser.y
- parser_test.go
Fix #1218
The with clause should be set before setOprStmt, not selectStmt. 
For example:
with cte as (select 1) select 1 union select 2;
The with clause should be added on the SetOprStmt, not the first selectStmt.
See the added tests.
Tests 
- Unit test
Code changes
Side effects
> fix CTE parser

- lexer.go
- parser_test.go
https://github.com/pingcap/tidb/issues/24429
when the sql_mode contains `ANSI_QUOTES`, the `stringlit` token will convert to `identifier`. so that we have to set the `identifierDot`(see https://github.com/pingcap/parser/pull/1132) to false.
Tests 
- Unit test
> lexer: fix lexer get wrong token

- mysql/privs.go
- mysql/privs_test.go
Fix mysql grant action compatibility
related to https://github.com/pingcap/tidb/issues/24439
related to https://github.com/pingcap/tidb/pull/24485
Add  StaticGlobalOnlyPrivs in privs.go
Tests 
- Unit test
- No code
Code changes
Side effects
> parser: Fix tidb issue 24439 Inconsistent error with MySQL for GRANT CREATE USER ON <specific db>.*

- parser.y
- parser_test.go
To Compatible with MySQL syntax. Fix [pingcap/tidb#24496](https://github.com/pingcap/tidb/issues/24496)
Add `SelectStmtGroup` in `SelectStmtBasic` block in parser.y
Tests 
- Unit test
```sql
mysql> select 1 group by 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```
> parser: Compatible with mysql fix `select 1 group by 1`

- lexer.go
- parser_test.go
close https://github.com/pingcap/parser/issues/1203
cherry-pick https://github.com/pingcap/parser/pull/1228
`identifierDot` should be true if and only if a dot after an identifier, if it is true, the next token must be interpreted as identifier or '*'
Tests 
- Unit test
> lexer: fix the bug that lexer may scan wrong tokens

- circle.yml
The Integration Test output currently has this:
```
note: module requires Go 1.16
```
This changes the container image used by CI
This is basically a copy of #1238 as I can't reopen that one.
> CI: Use Go 1.16 instead of Go 1.13

- auth/caching_sha2.go
- auth/caching_sha2_test.go
This code intended to set the first bit of every byte of the salt
to 0 as the salt should not contain multi-byte UTF-8.
However it failed to do this. This changes the `^` with a `^&` to fix
that.
In addition to that this also avoids the '$' inside salts as that is
already used as delimiter in the authentication string.
Tests 
- Unit test
This is related to https://github.com/pingcap/tidb/pull/24991
> auth: Fix salt generation of caching_sha2_password

- ast/misc.go
- auth/caching_sha2.go
- parser_test.go
This fixes issues found in the JDBC test cases:
- Allow `CREATE USER ... IDENTIFIED WITH <auth_method>` (without `'BY <password>`)
This also includes a fix for `NUL` in salts that was meant to be included in another PR but accidentally wasn't pushed.
Tests 
- Unit test
> auth: check for NUL in caching_sha2_password salt

- auth/caching_sha2.go
- auth/caching_sha2_test.go
- a NUL or '$' could get replaced with another NUL or '$'
- Replacement characters didn't get their first bit set to 0 (`&^ 128`)
- The test case used the index number instead of the value of the rune.
Related to https://github.com/pingcap/tidb/pull/24991
Tests 
- Unit test
> auth: caching_sha2_password salt fix

- parser.y
- parser_test.go
Fix https://github.com/pingcap/tidb/issues/25531
Updated parser.y by moving ODBC-styled literal codes to 'SimpleExpr'(same with MySQL: https://github.com/mysql/mysql-server/blob/3e90d07c3578e4da39dc1bce73559bbdf655c28c/sql/sql_yacc.yy#L10447)
Tests 
- Unit test
- Manual test(the one in https://github.com/pingcap/tidb/issues/25531)
Side effects
> parser: fix the usage of ODBC-styled time literal

- ast/expressions_test.go
- parser.y
Cherry-pick #1254 to release-4.0
Fix #1251 
When applying NOT to an ExistsSubqueryExpr, flip its `Not` flag instead of always setting it to `true`.
Tests 
- Unit test
Code changes
Side effects
* `NOT NOT EXISTS (SELECT ...)` is now correctly interpreted as `EXISTS (SELECT ...)`.
> parser: ensure NOT NOT EXISTS is the same as EXISTS (#1254)

- model/ddl.go
Signed-off-by: JaySon-Huang <tshent@qq.com>
Related to https://github.com/pingcap/tidb/issues/25507
Seems that we don't need to export the const `AddIndexStr` nor `AddPrimaryKeyStr` anymore after https://github.com/pingcap/tidb/pull/26218
Tests 
- No code
Code changes
Side effects
- N/A
- N/A
> Remove useless const AddIndexStr,AddPrimaryKeyStr

- ast/ddl.go
- mysql/type.go
- parser.y
- parser_test.go
close part of https://github.com/pingcap/tidb/issues/26580
support drop placement policy pattern
Tests 
- Unit test
> parser: support drop placement policy

- goyacc/main.go
- hintparser.go
- lexer.go
- yy_parser.go
https://github.com/pingcap/parser/pull/984 may introduce an incorrect implementation: it may write the AST nodes parsed previously. For details, see https://github.com/pingcap/tidb/issues/26538#issuecomment-893316891.
This PR provides an option to skip position recording.
Tests 
- Unit test
Code changes
Side effects
NA
> goyacc: add a config option to skip text position recording

- charset/charset.go
- charset/charset_test.go
- digester.go
- misc.go
- parser.y
- use a map to store the charset info directly
- remove `Desc` struct, it is definitely same with `Charset`
Tests 
- Unit test
Code changes
> charset: clean up some code about charset

- ast/ddl.go
- model/ddl.go
- parser.y
- parser_test.go
support create and alter placement policy
add syntax for 
1: `create placement policy if not exists x placement_opts`
2: `alter placement policy if exists x placement_opts`
this is based on https://github.com/pingcap/parser/pull/1299, wait for it merged first.
Tests 
- Unit test
> parser: support create and alter placement policy

- parser.y
- parser_test.go
Signed-off-by: xhe <xw897002528@gmail.com>
`placement` is not a keyword in mysql. Precedence is used to avoid ambiguity.
Tests 
- Unit test
> move placement into not keywords

- mysql/const.go
Signed-off-by: ailinkid <314806019@qq.com>
Add customized release version config option which will be initialized in the TiDB makefile.
Add customized release version config option which will be initialized in the TiDB makefile.
Related-TiDB-PR https://github.com/pingcap/tidb/pull/27692
Tests 
> mysql: add customized release version config option

- .github/CODEOWNERS
We don't use CODEOWNERS, also the information is incorrect.
> settings: Delete CODEOWNERS

- model/model.go
Signed-off-by: ailinkid <314806019@qq.com>
particial close https://github.com/pingcap/tidb/issues/26581
Since we want to store the direct placement option and policy ref into tableInfo, we better move the policyInfo and it's sub struct to parser, which will eliminate the dependency from parser ---> TiDB
move placement policy definition into 2 parser
Tests 
- No code
> model: move placement policy definition into 2 parser

- ast/misc.go
- mysql/const.go
Add `auth_socket` as authentication method, which is used by https://github.com/pingcap/tidb/pull/27561
Tests 
> Add 'auth_socket'

- ast/expressions.go
- format/format.go
- parser_test.go
To fix https://github.com/pingcap/tidb/issues/27544.
Now when restoring an expression, the parser doesn't add brackets for binary operations, which may change the meaning of the expression after restoring.
For example, `mod( year(a) - abs(weekday(a) + dayofweek(a)), 4) + 1` will be restored to `YEAR(a)-ABS(WEEKDAY(a)+DAYOFWEEK(a))%4+1`.
Introduce a new restore flag RestoreBracketAroundBinaryOperation to control this behavior.
Tests 
- Unit test
> introduce a new Restore Flag RestoreBracketAroundBinaryOperation

- go.mod
- model/model_test.go
Signed-off-by: ailinkid <314806019@qq.com>
In https://github.com/pingcap/parser/pull/1327 we move policyInfo into parser but the related test case.
So this pr move the missed policyInfo test from TiDB repo to Parser repo
move some tests.
Tests 
- Unit test
> parser: move policyinfo test from tidb to parser

- parser.y
- parser_test.go
Using `BINARY` in SET statements gets a syntax error because it is a keyword.
```sql
mysql> set @@character_set_results = binary;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 36 near ""
```
MySQL handled this problem by adding a rule:
https://github.com/mysql/mysql-server/blob/beb865a960b9a8a16cf999c323e46c5b0c67f21f/sql/sql_yacc.yy#L15902
Add a rule for `SetExpr`.
Tests 
- Unit test
Code changes
NA
Side effects
NA
NA
> parser: support 'binary' symbol in set statements

- ast/dml.go
- parser.y
- parser_test.go
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
For a multi-table join, a for update stmt locks all tables, some tables may only be read-only tables that participate in it.
Supports the of tables syntax, which specifies that only some of the tables are locked.
Tests
> *: support select for update of tables

- mysql/const.go
MaxDurationWidthWithFsp is wrong.
`time` is from `-838:59:59.000000` to `838:59:59.000000`.
Tests 
- No code
Code changes
Side effects
> mysql: fix MaxDurationWidthWithFsp

- ast/ddl.go
- charset/encoding.go
- charset/encoding_table.go
- charset/encoding_test.go
- lexer.go
- parser.y
- parser_test.go
- yy_parser.go
Required by https://github.com/pingcap/tidb/pull/27875
- Make `FindNextCharacterLength` only be used in the decoding process.
- Add some test for `Encoding`.
Tests 
- Unit test
Code changes
NA
Side effects
NA
NA
> charset: fix Encoding.Encode() and add some tests

- model/ddl.go
support database placement option and partition placement option
Tests 
- Unit test
- No code
Code changes
Side effects
> model: support database placement option and partition placement option

- lexer.go
- lexer_test.go
https://github.com/pingcap/parser/issues/1348
Implemeted LexLiteral() to global so that other packages can take advantage of Scanner.Lex() to analyze words. For example, other packages can use LexLiteral() to judge if the string is integer, decimal, etc.
Add a method to Scanner called LexLiteral() that simple returns the value of item after lexical analysis
Tests 
- Unit test
Code changes
None
Side effects
None
> Implement interface for acquiring literal value
